<?php

namespace App\Filament\Pages;

use App\Models\Race;
use Filament\Pages\Page;
use Illuminate\Contracts\Support\Htmlable;

class StartRace extends Page
{
    protected static string $view = 'filament.pages.start-race';

    public function getTitle(): string|Htmlable
    {
        return Race::find(request('id'))->name; // TODO: Change the autogenerated stub
    }

    protected static bool $shouldRegisterNavigation = false;
}
